# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: services.proto for package 'grpc.greeter'
# Original file comments:
# 1. syntax, package, option

require 'grpc'
require 'services_pb'

module Grpc
  module Greeter
    module GreetingService
      # 4. service, unary request/response
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'grpc.greeter.GreetingService'

        rpc :greeting, HelloRequest, HelloResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
