# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpc.greeter.HelloRequest" do
    optional :msg, :string, 1
  end
  add_message "grpc.greeter.HelloResponse" do
    optional :greeting, :string, 1
  end
end

module Grpc
  module Greeter
    HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.greeter.HelloRequest").msgclass
    HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.greeter.HelloResponse").msgclass
  end
end
