# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services_pb2 as services__pb2


class GreetingServiceStub(object):
  """4. service, unary request/response
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.greeting = channel.unary_unary(
        '/grpc.greeter.GreetingService/greeting',
        request_serializer=services__pb2.HelloRequest.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )


class GreetingServiceServicer(object):
  """4. service, unary request/response
  """

  def greeting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreetingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'greeting': grpc.unary_unary_rpc_method_handler(
          servicer.greeting,
          request_deserializer=services__pb2.HelloRequest.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.greeter.GreetingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
